apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webserver
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/cmcornejocrespo/rhacm-workshop.git
      revision: main
      files:
      - path: "04.Application-Lifecycle/exercise-argocd/argocd-resources/environments/**/cluster.json"
  - git:
      repoURL: https://github.com/cmcornejocrespo/rhacm-workshop.git
      revision: main
      directories:
      - path: 04.Application-Lifecycle/exercise-argocd/application-resources/values/*
  template:
    metadata:
      name: '{{application_name}}'
    spec:
      project: demo-project-argocd
      source:
        repoURL: https://github.com/cmcornejocrespo/rhacm-workshop.git
        targetRevision: main
        path: 04.Application-Lifecycle/exercise-argocd/application-resources/
        helm:
          valueFiles:
          - 'values/{{application_name}}/values.yaml'
      destination:
        name: '{{cluster.name}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
