apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mariadb
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: quay.io/centos7/mariadb-103-centos7
          ports:
            - containerPort: 3306
              name: db-port  
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: mariadb