apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: mariadb
    type: database
spec:
  labels:
    app: mariadb
    type: database
stringData:
    database-root-password: jjhg6sSS